
@REM WARNING ERROR STATUS VERBOSE TRACE
set CMAKE_LOGLEVEL=--log-level=VERBOSE 

set CMAKE_BUILD_TYPE=Release
cmake -S . -B build %CMAKE_LOGLEVEL% -DCMAKE_BUILD_TYPE:String=%CMAKE_BUILD_TYPE% 

set CMAKE_PARALLEL_JOBS=--parallel 8
@REM set CMAKE_PARALLEL_JOBS=-j8
set CMAKE_BUILD_VERBOSE=--verbose
cmake --build build --target %1 %CMAKE_PARALLEL_JOBS% %CMAKE_BUILD_VERBOSE%
